services:
  mqtt-influx-subscriber:
    build: .
    container_name: mqtt-influx-subscriber
    restart: unless-stopped
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_TOPIC: homelab/pi5/dht22/metrics

      INFLUX_URL: http://host.docker.internal:8086
      INFLUX_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      INFLUX_ORG: homelab
      INFLUX_BUCKET: sensors
    extra_hosts:
      - "host.docker.internal:host-gateway"
