global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-debian01'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'debian01'

  - job_name: 'cadvisor-debian01'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'debian01'

  - job_name: 'node-pi5'
    static_configs:
      - targets: ['192.168.2.148:9100']
        labels:
          instance: 'pi5'

  - job_name: 'influxdb'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8086']
